name: Branch Others workflow

on:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  buildAndTest:
    name: Build-angular
    runs-on: ubuntu-latest
    steps:
      - name: build_test_ext
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build-angular-workflow
          token: ${{ secrets.USER_GITHUB_TOKEN }}
          display-workflow-run-url: true
          display-workflow-run-url-timeout: 10m
          display-workflow-run-url-interval: 15s
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 15s
